### ISSUE TITLE
use with bacterial genome assemblies?

### ISSUE THREAD

**Issue by apsteinberg** [niemasd/ViralMSA#16]
Hi,

Thanks for creating this very useful tool! I was wondering if there is any reason why this would not work with aligning bacterial genome assemblies to a reference genome? It seems like it should work just fine, but I didn't see any mention of this in your paper so I figured I would ask before I gave it a go.

**Comment by niemasd** [comment]
Hey! No particular reason: I just focus on viral genomes because I made this specifically with the intention of speeding up viral phylogenetic workflows (namely SARS-CoV-2). I imagine it should work well for any scenario in which you expect all query genomes to be fairly similar to the reference!

It also only supports a single reference sequence, but for organisms with multiple sequences (e.g. multiple chromosomes), you could probably separate out homologous sequences and run ViralMSA on each separately!

Feel free to try it out, and let me know how it goes! :-)

**Comment by apsteinberg** [comment]
Great! Sounds good, I'll give it a go and keep you posted -- thanks for the quick reply! :)
